collector-a:
  mode: "deployment"
# uncomment and provide config for collector a
#  config:
collector-b:
  mode: "deployment"
# uncomment and provide config for collector b
#  config:
opentelemetry-demo:
  opentelemetry-collector:
    config:
      exporters:
        otlp/a:
          endpoint: '{{ include "otel-demo.name" . }}-collector-a:4317'
          tls:
            insecure: true
        otlp/b:
          endpoint: '{{ include "otel-demo.name" . }}-collector-b:4317'
          tls:
            insecure: true
      service:
        pipelines:
          traces: &basic
            receivers: [ otlp ]
            processors: [ batch ]
            exporters: [ logging, otlp/a, otlp/b ]
          metrics: *basic
          logs: *basic
  default:
    envOverrides:
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: >-
          service.name=$(OTEL_SERVICE_NAME),
          k8s.namespace.name=$(OTEL_K8S_NAMESPACE),
          k8s.node.name=$(OTEL_K8S_NODE_NAME),
          k8s.pod.name=$(OTEL_K8S_POD_NAME),
          deployment.environment=opentelemetry-demo
  observability:
    jaeger:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
  components:
    loadgenerator:
      envOverrides:
        - name: LOCUST_HEADLESS
          value: "true"
